version: '3.8'

services:
  sentinel-redis:
    image: redis:alpine
    container_name: sentinel-redis
    ports:
      - "6379:6379"
    # This ensures Redis saves tasks to disk so they survive restarts
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_persistent_data:/data

volumes:
  redis_persistent_data: